python K_means.py 3 data.csv > 3_prueba1.txt
python K_means.py 3 data.csv > 3_prueba2.txt
python K_means.py 3 data.csv > 3_prueba3.txt
python K_means.py 3 data.csv > 3_prueba4.txt
python K_means.py 3 data.csv > 3_prueba5.txt
python K_means.py 3 data.csv > 3_prueba6.txt
python K_means.py 3 data.csv > 3_prueba7.txt
python K_means.py 3 data.csv > 3_prueba8.txt
python K_means.py 3 data.csv > 3_prueba9.txt
python K_means.py 3 data.csv > 3_prueba10.txt

python K_means.py 5 data.csv > 5_prueba1.txt
python K_means.py 5 data.csv > 5_prueba2.txt
python K_means.py 5 data.csv > 5_prueba3.txt
python K_means.py 5 data.csv > 5_prueba4.txt
python K_means.py 5 data.csv > 5_prueba5.txt
python K_means.py 5 data.csv > 5_prueba6.txt
python K_means.py 5 data.csv > 5_prueba7.txt
python K_means.py 5 data.csv > 5_prueba8.txt
python K_means.py 5 data.csv > 5_prueba9.txt
python K_means.py 5 data.csv > 5_prueba10.txt

python K_means.py 10 data.csv > 10_prueba1.txt
python K_means.py 10 data.csv > 10_prueba2.txt
python K_means.py 10 data.csv > 10_prueba3.txt
python K_means.py 10 data.csv > 10_prueba4.txt
python K_means.py 10 data.csv > 10_prueba5.txt
python K_means.py 10 data.csv > 10_prueba6.txt
python K_means.py 10 data.csv > 10_prueba7.txt
python K_means.py 10 data.csv > 10_prueba8.txt
python K_means.py 10 data.csv > 10_prueba9.txt
python K_means.py 10 data.csv > 10_prueba10.txt

python K_means.py 11 data.csv > 11_prueba1.txt
python K_means.py 11 data.csv > 11_prueba2.txt
python K_means.py 11 data.csv > 11_prueba3.txt
python K_means.py 11 data.csv > 11_prueba4.txt
python K_means.py 11 data.csv > 11_prueba5.txt
python K_means.py 11 data.csv > 11_prueba6.txt
python K_means.py 11 data.csv > 11_prueba7.txt
python K_means.py 11 data.csv > 11_prueba8.txt
python K_means.py 11 data.csv > 11_prueba9.txt
python K_means.py 11 data.csv > 11_prueba10.txt